#!/bin/tcsh

source /etc/profile.d/modules.csh

setenv LC_ALL "C"
set path = `echo $path | tr ' ' '\n' | grep -v '/ifs/home/'`
module unload r
module unload python
module load r/3.6.1
#module load python/cpu/3.6.5
module load samtools/1.9
module load bedtools/2.27.1
module load java/1.8
module load gsl/2.5
module load gtools/3.0.0

#umask 007


