#!/bin/bash
	module load fastqc/0.11.7
	module load parallel/20231222

	if test ! -d ./out/QC
	then
		mkdir ./out/QC
	fi

###FastQC for raw data
	if [ -d data/Fastq ] && [ -n "$(ls -A data/Fastq)" ]
	then
		if test ! -d ./out/QC/raw
		then
			mkdir ./out/QC/raw
		fi
		fastqc -t 8 -q data/Fastq/*.fastq.gz -o out/QC/raw
		#conda activate multiQC_env
		#multiqc -o out/QC/raw -f out/QC/raw
		#conda deactivate
	fi

